// GENERATED by scripts/build-buildings.mjs -- do not edit by hand.
// Campus building coordinates, baked at build time so answering
// "what's near PMU" costs no network hop. Buildings do not move.
export type Building = { name: string; lat: number; lon: number };
export const BUILDINGS: Record<string, Building> = {
  "ELLT": {
    "name": "Elliott Hall of Music",
    "lat": 40.427896,
    "lon": -86.915007
  },
  "PHYS": {
    "name": "Physics Building",
    "lat": 40.430102,
    "lon": -86.913451
  },
  "BRWN": {
    "name": "Brown Laboratory of Chemistry",
    "lat": 40.426583,
    "lon": -86.911963
  },
  "ARMS": {
    "name": "Neil Armstrong Hall of Engr",
    "lat": 40.430918,
    "lon": -86.914984
  },
  "RHPH": {
    "name": "Robert Heine Pharmacy Building",
    "lat": 40.429744,
    "lon": -86.915971
  },
  "STEW": {
    "name": "Stewart Center",
    "lat": 40.425084,
    "lon": -86.912711
  },
  "KNOY": {
    "name": "Knoy Hall of Technology",
    "lat": 40.427808,
    "lon": -86.911091
  },
  "JNSN": {
    "name": "Johnson Hall of Nursing",
    "lat": 40.429403,
    "lon": -86.915523
  },
  "WTHR": {
    "name": "Wetherill Lab of Chemistry",
    "lat": 40.426469,
    "lon": -86.9131
  },
  "DSAI": {
    "name": "Hall of Data Science and AI",
    "lat": 40.428971,
    "lon": -86.914858
  },
  "HAMP": {
    "name": "Hampton Hall of Civil Engnrng",
    "lat": 40.430237,
    "lon": -86.914766
  },
  "FRNY": {
    "name": "Forney Hall of Chemical Engr",
    "lat": 40.429519,
    "lon": -86.914008
  },
  "SCHM": {
    "name": "Helen B. Schleman Hall",
    "lat": 40.425807,
    "lon": -86.915209
  },
  "HAAS": {
    "name": "Felix Haas Hall",
    "lat": 40.426823,
    "lon": -86.916311
  },
  "POTR": {
    "name": "Potter Engineering Center",
    "lat": 40.427539,
    "lon": -86.912403
  },
  "AR": {
    "name": "Armory",
    "lat": 40.428016,
    "lon": -86.916277
  },
  "MTHW": {
    "name": "Matthews Hall",
    "lat": 40.424746,
    "lon": -86.916379
  },
  "PSYC": {
    "name": "Psychological Sciences Bldg",
    "lat": 40.426965,
    "lon": -86.914959
  },
  "BRNG": {
    "name": "Beering Hall of Lib Arts & Ed",
    "lat": 40.425575,
    "lon": -86.916061
  },
  "MATH": {
    "name": "Mathematical Sciences Building",
    "lat": 40.426254,
    "lon": -86.91583
  },
  "STON": {
    "name": "Winthrop E. Stone Hall",
    "lat": 40.424666,
    "lon": -86.915381
  },
  "YONG": {
    "name": "Ernest C. Young Hall",
    "lat": 40.422848,
    "lon": -86.910646
  },
  "NLSN": {
    "name": "Nelson Hall of Food Science",
    "lat": 40.421565,
    "lon": -86.915494
  },
  "MJIS": {
    "name": "Jischke Hall of Biomedical Eng",
    "lat": 40.422184,
    "lon": -86.920912
  },
  "ABE": {
    "name": "Agricultural & Biological Engr",
    "lat": 40.421704,
    "lon": -86.916618
  },
  "BRES": {
    "name": "Brees Student-Athlete Acad Ctr",
    "lat": 40.43412,
    "lon": -86.916571
  },
  "MSEE": {
    "name": "Materials and Electrical Engr",
    "lat": 40.429341,
    "lon": -86.91267
  },
  "EE": {
    "name": "Electrical Engineering Bldg",
    "lat": 40.428637,
    "lon": -86.911964
  },
  "ME": {
    "name": "Mechanical Engineering Bldg",
    "lat": 40.428296,
    "lon": -86.912879
  },
  "HIKS": {
    "name": "Hicks Undergraduate Library",
    "lat": 40.424535,
    "lon": -86.912657
  },
  "UNIV": {
    "name": "University Hall",
    "lat": 40.42527,
    "lon": -86.915193
  },
  "BCC": {
    "name": "Black Cultural Center",
    "lat": 40.427525,
    "lon": -86.919517
  },
  "LWSN": {
    "name": "Lawson Computer Science Bldg",
    "lat": 40.427796,
    "lon": -86.916995
  },
  "MRGN": {
    "name": "Morgan Ctr for Entrepreneurshp",
    "lat": 40.423753,
    "lon": -86.922846
  },
  "NISW": {
    "name": "Niswonger Aviation Tech Bldg",
    "lat": 40.416383,
    "lon": -86.929444
  },
  "HOCK": {
    "name": "Hockmeyer Hall Strc Bio",
    "lat": 40.421202,
    "lon": -86.921179
  },
  "DLR": {
    "name": "Discovery and Learning",
    "lat": 40.421224,
    "lon": -86.92244
  },
  "FWLR": {
    "name": "Fowler Memorial House",
    "lat": 40.424889,
    "lon": -86.922262
  },
  "TERM": {
    "name": "Terminal Building (Hangar 2)",
    "lat": 40.416245,
    "lon": -86.930974
  },
  "SIML": {
    "name": "Holleman-Niswonger Simultr Ctr",
    "lat": 40.416694,
    "lon": -86.934978
  },
  "WANG": {
    "name": "Seng-Liang Wang Hall",
    "lat": 40.430461,
    "lon": -86.912541
  },
  "AACC": {
    "name": "Asian Amer & Asian Cult Ctr",
    "lat": 40.42913,
    "lon": -86.917654
  },
  "CL50": {
    "name": "Class of 1950 Lecture Hall",
    "lat": 40.426347,
    "lon": -86.915058
  },
  "PRCE": {
    "name": "Peirce Hall",
    "lat": 40.426629,
    "lon": -86.915055
  },
  "KRCH": {
    "name": "Krach Leadership Center",
    "lat": 40.427589,
    "lon": -86.921245
  },
  "WALC": {
    "name": "Wilmeth Active Learning Center",
    "lat": 40.427389,
    "lon": -86.913229
  },
  "BIDC": {
    "name": "Bechtel Innovation Design Ctr",
    "lat": 40.427522,
    "lon": -86.918798
  },
  "FLEX": {
    "name": "Flex Lab",
    "lat": 40.421532,
    "lon": -86.923645
  },
  "CHAS": {
    "name": "Chaney-Hale Hall of Science",
    "lat": 40.428592,
    "lon": -86.915524
  },
  "CRTN": {
    "name": "Creighton Hall of Animal Sci",
    "lat": 40.421102,
    "lon": -86.918869
  },
  "LYLE": {
    "name": "Lyles-Porter Hall",
    "lat": 40.420934,
    "lon": -86.91676
  },
  "HAGL": {
    "name": "Marc & Sharon Hagle Hall",
    "lat": 40.427067,
    "lon": -86.918823
  },
  "LMBS": {
    "name": "Lambertus Hall",
    "lat": 40.427588,
    "lon": -86.911645
  },
  "DUDL": {
    "name": "Dudley Hall",
    "lat": 40.427141,
    "lon": -86.911279
  },
  "SC": {
    "name": "Stanley Coulter Hall",
    "lat": 40.426528,
    "lon": -86.914382
  },
  "WILY": {
    "name": "Harvey W. Wiley Residence Hall",
    "lat": 40.429503,
    "lon": -86.920719
  },
  "GRIS": {
    "name": "Grissom Hall",
    "lat": 40.426439,
    "lon": -86.910917
  },
  "CHAF": {
    "name": "Chaffee Hall",
    "lat": 40.41608,
    "lon": -86.94265
  },
  "HORT": {
    "name": "Horticulture Building",
    "lat": 40.421714,
    "lon": -86.91443
  },
  "UC": {
    "name": "University Church",
    "lat": 40.426134,
    "lon": -86.909905
  },
  "SMTH": {
    "name": "Smith Hall",
    "lat": 40.423401,
    "lon": -86.916866
  },
  "BCHM": {
    "name": "Biochemistry Building",
    "lat": 40.422872,
    "lon": -86.916553
  },
  "VPTH": {
    "name": "Veterinary Pathology Building",
    "lat": 40.420019,
    "lon": -86.915525
  },
  "ADDL": {
    "name": "Animal Disease Diagnostic Lab",
    "lat": 40.418153,
    "lon": -86.916014
  },
  "PKRW": {
    "name": "Winifred Parker Residence Hall",
    "lat": 40.427846,
    "lon": -86.920334
  },
  "SCHW": {
    "name": "Schwartz Tennis Center",
    "lat": 40.436648,
    "lon": -86.938144
  },
  "HILL": {
    "name": "Hillenbrand Residence Hall",
    "lat": 40.426695,
    "lon": -86.926698
  },
  "EHSA": {
    "name": "Equine Health Sciences Annex",
    "lat": 40.417555,
    "lon": -86.914211
  },
  "BIND": {
    "name": "Bindley Bioscience Center",
    "lat": 40.422772,
    "lon": -86.923418
  },
  "HLAB": {
    "name": "Herrick Laboratories",
    "lat": 40.42281,
    "lon": -86.920947
  },
  "SF": {
    "name": "State Farm",
    "lat": 40.421095,
    "lon": -86.902861
  },
  "AGAD": {
    "name": "Agricultural Administration",
    "lat": 40.423362,
    "lon": -86.914409
  },
  "STDM": {
    "name": "Ross-Ade Stadium",
    "lat": 40.434652,
    "lon": -86.918454
  },
  "SH": {
    "name": "South Hall",
    "lat": 40.425856,
    "lon": -86.92665
  },
  "PMU": {
    "name": "Purdue Memorial Union",
    "lat": 40.4249,
    "lon": -86.91095
  },
  "KRAN": {
    "name": "Krannert Building",
    "lat": 40.42368,
    "lon": -86.91094
  },
  "RAWL": {
    "name": "Jerry S Rawls Hall",
    "lat": 40.42369,
    "lon": -86.90978
  },
  "BHEE": {
    "name": "Max W & Maileen Brown Hall",
    "lat": 40.425575,
    "lon": -86.916061
  },
  "HICKS": {
    "name": "Hicks Undergraduate Library",
    "lat": 40.424535,
    "lon": -86.912657
  }
};
